#!/bin/bash

PIDFILE=/var/run/opticon-agent.pid
AGENT=$(which opticon-agent)
if [ -z "$AGENT" ]; then
    [ -e /usr/local/sbin/opticon-agent ] && AGENT="/usr/local/sbin/opticon-agent"
    [ -e /config/scripts/opticon-agent ] && AGENT="/config/scripts/opticon-agent"
    [ -e ./opticon-agent ] && AGENT="./opticon-agent"
fi

[ -z "$AGENT" ] && exitfail "Could not find agent"

if [ "$AGENT" = "/config/scripts/opticon-agent" ]; then
  if [ ! -d /etc/opticon ]; then
    mkdir /etc/opticon
    id opticon >/dev/null 2>&1 || {
      useradd -M -r -U opticon
    }
    chgrp opticon /etc/opticon
    chmod 750 /etc/opticon
    ln -s /config/opticon-agent.conf /etc/opticon/opticon-agent.conf
    ln -s /config/opticon-defaultprobes.conf /etc/opticon/opticon-defaultprobes.conf
  fi
fi

case "$1" in
    start)
        $AGENT
        ;;
    
    stop)
        [ -e $PIDFILE ] && kill -TERM $(cat $PIDFILE)
        ;;
    
    restart)
        [ -e $PIDFILE ] && kill -TERM $(cat $PIDFILE)
        $AGENT
        ;;
        
    *)
        exitfail "Usage: $0 <start | stop | restart>"
        ;;
esac
