#!/bin/bash

get_ifchoice() {
 sz=$(ip link show up | grep "^[0-9]" | cut -f2 -d: | grep -v lo | grep -v vnet | wc -l)
 printf "$sz "
 ip link show up | grep "^[0-9]" | cut -f2 -d: | grep -v lo | grep -v vnet \
                 | while read if; do
    xtra="          "
    on="OFF"
    if [ "$if" = "$1" ]; then
        xtra="Default gateway.    "
        on="ON"
    fi
    printf '"'"$if"'" "'"  $xtra"'" '"$on "
  done
}

display_ifchoice() {
  local title="$1"
  shift
  local text="$1"
  shift
  
  gatewayif=$(ip route get 8.8.8.8 | head -n1 | awk '{print $5}')
  choice=$(get_ifchoice $gatewayif)
  eval whiptail --title \"$title\" --checklist \"$text\" 20 50 "$choice"
}

menu_ifchoice() {
  t="Select interface(s) to use for general traffic monitoring."
  t="$t These should be interfaces facing other networks."
  display_ifchoice "Traffic monitor" "$t"
}

run_tenantid() {
  local title="$1"
  shift
  local text="$1"
  shift
  out=$(mktemp /tmp/osetup-XXXXXXXXXX)
}

display_tenantid() {
  local title="$1"
  shift
  local text="$1"
  shift
  tidvalid=0
  tid=""
  
  while [ $tidvalid = 0 ]; do
    tid=$(whiptail --title "$title" --inputbox "$text" 8 50 --default-item "$tid" 3>&1 1>&2 2>&3)
    if [[ $tid =~ ^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$ ]]; then
      tidvalid=1
    fi
  done
  echo "$tid" | tr A-F a-f
}

menu_tenantid() {
  t="Enter your tenant UUID"
  display_tenantid "Tenant" "$t"
}

menu_tenantid
